### ISSUE TITLE
RestSharp upgrade to 108

### ISSUE THREAD

**Issue by E-PressSend** [Chinchilla-Software-Com/HubSpot.NET#26]
Hi Guys, 

I'm getting an error while running my app which is caused by the fact that another dependency uses the RestSharp v108, while HubSpot.NET uses version 106.

Is there any plan to upgrade this library to RestSharp 108? is that very time consuming?

this is the error I'm getting while using HubSpot.NET:

````
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: CreateTicket
 ---> System.TypeLoadException: Could not load type 'RestSharp.IRestRequest' from assembly 'RestSharp, Version=108.0.1.0, Culture=neutral, PublicKeyToken=598062e77f915f75'.
   at HubSpot.NET.Core.HubSpotBaseClient.SendRequest(String path, Method method, String json)
   at HubSpot.NET.Core.HubSpotBaseClient.SendRequest[T](String path, Method method, String json, Func`2 deserializeFunc)
   at HubSpot.NET.Api.Company.HubSpotCompanyApi.GetByDomain[T](String domain, CompanySearchByDomain options)
...
````

Cheers

**Comment by middiu** [comment]
raised PR #28 to resolve this issue.
